---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54"
