---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf"
