---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  flux: .taskfiles/Flux/Taskfile.yaml
  repository:
    aliases: ["repo"]
    taskfile: .taskfiles/Repository/Taskfile.yaml
  talos: .taskfiles/Talos/Taskfile.yaml
  sops: .taskfiles/Sops/Taskfile.yaml
  workstation: .taskfiles/Workstation/Taskfile.yaml
  user:
    taskfile: .taskfiles/User
    optional: true
  volsync: .taskfiles/VolSync/Taskfile.yaml
  ExternalSecret:
    alias: ["es"]
    taskfile: .taskfiles/ExternalSecrets/Taskfile.yaml
tasks:

  default: task -l

