apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:QxlxRe7kGTMHvQUgk1Qp/3ARYnnc5krR0jZX4Me4hg/piZeS,iv:fhaa5efIOGc0iwWxANSC+8MAjsODg6pboDWZpQn00j0=,tag:NNyOkP78dV5VAM8e7EkaDg==,type:str]
    credentials.json: ENC[AES256_GCM,data:XK93ZczhfgJDAnxTbBRFpXBnRpmRf35izlomag6K5T4GNnx/0jXTIrh/OO96EegrRxgTiva9PBoaZOUr1w6Ped3xLSB1wAKqKrwPME4pJ4W+i7lfKU3P+LIJ5uMgVGIRvfhxopQyslm2eXkOv2oxCT5iWQrRaaeVuDZ4Z40L6wZucfLTbDeCa6qEtBaBGnpYf9sIhJzqEuc8PcpjSLPNs3h9FZPYupWhROLUfwAVKA==,iv:pyKp5B1xu7YXDtyBHpLI5QyXpKu1UwHFKlm98Y5z0+I=,tag:mDjrRQ1Ul6of+QBryjbdPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0RtejNhTEpJMVFzekdS
            cjJVVVAvNDNMNFkwUGV2WnE4OXFCcDlwRjNvCkZMNm5BUHNITll0d3BBWWE0eFZv
            bXk1N3FRb2QxZm9MdzI5anJvejBoTG8KLS0tIDVKalI1dlJyQ3RUZmszZ0RQRThS
            L3ppS0pyKytqZm50YnI2NUVwYUZweDAKhJZtDqn6z4IJKUSMpx3MrgsRpZCBJTOx
            RQXaK4cUzL1rffinXUQ1LksYDCLY99CBoAMXYrDun5RH700GtmKw/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T06:24:08Z"
    mac: ENC[AES256_GCM,data:hlgKPNbfPSaRgk27QEMLcWnUPeg0iSDVIZZ41ofC6V6Ri2hwa+j3hJuQ/G63Duo9EOB3FsYvy4gDzTGrMm6jnK/F/W68QCnab7WujvUfMXX+Wv2lM2HHI6RAicx41jcJ8gW0bL7JeBdCNN9J5bvbuQZaMcxTWdsToNuuKvAU+qs=,iv:6jC9xBAnOrLNtOQ79s6NjR1aV45qbnqcJILIvfZ4QNE=,tag:q3d+SRUiYef0iWZbYI8bUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
