apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RVMRcoP8+JY4wnMyQbqJuBmzJIL1/6CwjAUiFYF1uTG+iLHT,iv:O/z178zhsoNNdPwSTWYkPJ/l7bgEiRRI1ZEKAZtIWL4=,tag:E28DlYXRLzndMPZ+JIMphg==,type:str]
    credentials.json: ENC[AES256_GCM,data:gUw8Rn29bdvyO/rwaDWcCbMFrZvANEXauuaWGyRwi6yJAJSBcuckiYVToIk2NzbqVwvhwf3OAWtTdsQl6XLM5eaul1YLfwdvmVaLZneAWt/zBPzIyFTs2mi/my1InEARAMnK5m7PWNLRQhZWfHQwTR7fsQOZeE9J9wvYsIa0DlIyxFOrc7FmZ6o/bXUaVH35SenugsZVdduSq4AB7JcGbgPDmRdcn1h40aZSC2OckA==,iv:YdnXQiiW8CnB/ZQi3Gfz0uGBK4WyZ4hGmp+KUhazxOk=,tag:tIjY/PoM2SBM0Ft1wym/9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR2pOajVWR2J0WFo0by84
            NG1IdCtUWkE4aVRVa2dLRkhnbjlVY1hhZUVZCnVIeUJaMXUwNk5xcTk0cDMwRUg3
            S0d4RW4ydVBna2NOMUVabGhzL0tJdjgKLS0tIG9lK1hqM2xLdkpBZTduUWRRaXky
            TVE4dlQ5TnRYc3QwdXN5SXBzLzUwNG8K7s2FrY1D97B2KQbiXdztVE5bZfWfspnw
            3PQHiA7aLWUj2Zu05SbgMTybma6kGZfdGvUI6HvckpLOScxzEf1rQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T07:02:50Z"
    mac: ENC[AES256_GCM,data:K3Lv5I03iah8heEDscIuFPoxHSXKm2dAHMEAJx3vq5ktdSfPvi1iU8h6v7LvO+VS2T4zbJ84ojYJ1m2BsE0eIeGYr3h/ttZaaujTqdY7X+cCQ9d8q2U2PE63ISfCgVBq+Swc5QPrm43mrRrbv4iQtsnQN4eLaq6A/bn0i2r1QsA=,iv:0Maf+uWJs+5QHnlpWnrKgydacDwqHB8ueJNHFuiz6PU=,tag:dLlvzHTy3pwdzDVvVZCXAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
