apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:b+anJqgG4/SfT3D3fyYCTPYEDrwiPX161DgfM6zVW4ewPNSJ,iv:aUxP7/erzLJUdXVWIuspa3ywhSWluwCH2P1DrWNYJxo=,tag:wwZkPyydFbiAxrfAb3o0Og==,type:str]
    credentials.json: ENC[AES256_GCM,data:z+U0HDmp7pMbQKv4alITexvOtDZp42ZYdH9EqitFcJiY81+zy2p1j4YykErhKCzOkcYbIM6sIvWgqRStA5sWm7UGezNdZf+WnjFWoN7I4AW85srfqAuZZ1/dmU1UOlNv+qMLs8krScW+Stj5aeYn6CJw3Ekb/1EkLpuHQQpp9zzmJ1tgCD4+gZK/T0YQ+Pgu+jqqiLD70+cdCBOtRvmAs1M4RZqGh8P/LjSdGAFuAQ==,iv:coTR0HM2APdWabZZGa0bZdkbevgQSEvJiatr+lbJqMM=,tag:2fe9mtSpboOTYDCjGbBzOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2dWY2JBNkZmazZzbmJs
            WCtETklKOURuaC9JZHVVa2FuYnlYMERWRlF3CnRTWjdUTVVJZ1ExSEgzTG9qblFx
            Z2x6Zi8rNzczRnhHS1k5L1dCRkpMOE0KLS0tICt1cHk0cXNTTXhPazh1MUtvd0k0
            RzZrUHhDclJ5cm03SlBhZ2tuaDBBSW8KM/PZ4LrXQgT46/r9ePdmTOx3RlZCYT0+
            zg9blNmD7J4UCBpSPqMYkQgXyEHRJTRNRiMe6uboYf6GhqOWZDG1yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T05:19:20Z"
    mac: ENC[AES256_GCM,data:1qZb/rqo7+NyYN7Gs/94reXJmF942R7MEuqNAuLCgDTu93V1594rxQrdpZMVDqfcOi6qdirm8zz4OTKUPXDFMycQ5YsBES+RzpuSVT8gQ7cXLd43qwCk+QXfjQuvciEMPWybSpVGDUSTjMgnwRp7CN5QwAjh4RNgpxtErGOCBw0=,iv:6GmK6l+8iR5qbX3U1WZTNii9NN5uRJ+gJ+SJE2SGt30=,tag:pT71sQ7oj21hWqoCQ28rbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
