apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eGckes2KiHWF9nNs/FdBxfSII6NuRcFGnHfRG5ICjnBUMOrvy1FaRA==,iv:ftoqMH6mDWKPRi4XtMLnYLQtcc6NDnM1O7I3S1fMkyI=,tag:gGvRCSNQ8Ut3mdAm/JECkw==,type:str]
sops:
  age:
    - recipient: age1x04pdgvml4flx5lewxkqhp3rfngzlgt6gnhqnydskf9u9zhf7euq4qxxxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L0lJUFNuSmtETFk1N3JY
        dlh4LzE1WjZSbWM4dEcwOTVRTDVBeEsyZWx3CjdpTnc5MWIvOW00OU1kS2ljeGpW
        c29TcW9TVnV6aVdaYVNmRGl1aHJkUUEKLS0tIDczV1plNVE3WEFnUGE5S1JDM2cr
        dVlTTnBXbzVVeUMrMFBlQmNPV0dPZ0kK28VSc2g7Viza2Cbqn82pgy17REyVhneS
        X+B3AylsPe6YKnJjNw+I78hx7DhPXhjar8MnrvLqSkn/Jl1TfFuFxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T03:44:24Z"
  mac: ENC[AES256_GCM,data:sjXk8uRh45gwKJpV9vpo88bxRGCstE8rElnHzPidr3fgjc5GLEiORTPfv141ITZtUfQa2V8/FnHkHqZQxKgZvKp13ybarl6QIsHG+I7YadB4MnfW0Zw6jaJJsF/77FLFOs9Xo5kwe6IG/jHjiYrUBb9gMcL5/F+Pd1X8Ei3vP00=,iv:swtCjImhCemnvTOyXkaszAd4H60PbJz3M0sShRzaq4A=,tag:+o/5xgMsKscIZGqF58m7Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
