apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DQvegYrYowNXLs00844jNXuzdwT+jXy82EvDoKUDDqLXj8Fqf0CU7g==,iv:Gt5Z1csvxqVJiQWg/4TDTqbSr2I7GSk33V0pdneGDW0=,tag:NCVHEQSN6xUIcWZgviKvSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxV210Q05OM1lHbVZ5RHpk
            eitVOC9EU2VPYmY2djhzczIvMHhlTFUyUnlBCkFsMGpnTHRtNDhLSEFvRmZlNE4y
            VjZWWEw3Z29LQ2srbzZXYVlIemxDUGsKLS0tIG1uVHBSeTFaMTluaC9iNnFleThk
            UVQ0Sjlzd0xXMnVXb0pPR0VWa29BbkEKvspZ9yc7LMNALp+zweDP1wzMhnLJJ7gx
            mEWgX685361rZ/rwxK8E4EJsKEu5T/zM94KoUkFJJ2biG/J22Jz+VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T19:54:58Z"
    mac: ENC[AES256_GCM,data:LSxj7JMsXXzrjRfDy8pPlawKpGxH1Rrq6TDrAVQ2m0kpoFPexj/d2EB6LT3ta2xs/k7If2//b72aqtaWHHo5qKEa8XW6l3PvSrqLSdmM8FkvfGasXqe9c1KX8/HZ73OvKP4hEcDJ5sxyt4+pCiVWrZhI1OoQH3ToJy1h11Dj22E=,iv:36P59vkSeInrR/XSMd357bG8q4RS50P6EpI8ZXC2GZ8=,tag:lCRl51OwWR7okqOY5Ucrbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
