apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7lLEnDBXJje3wsXSdyZGpaoqsAFtqQTJYXP67NSxC0YhT8xL/NMO/A==,iv:zJIHiV0uuGm7U6XQtXQlyQ+MQQo/W5ESIsGtS26a+sc=,tag:BAdGAukU4eT2eiBzmwu3DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RlhJL2hGeVRwL09xZ2Fz
            RU1nQzhKVjkxb3A5bFJjYzJKckEyVWxyUGhFCitZSkU0Vzk0OXZ1QnBWQ1psRFV1
            NFJleWhFRjg5UVRrUUZkNzNxS2lScFEKLS0tIHVhTHVkdUpvQ0dCYUw0eEg0ZzFN
            eTNjK1FKd0hITXhPb2IxUDhGZmliWTAK4Fjj1oHkf5nXBgzE/VPrXfZeNKMagLpn
            +rdhlcgEGE58tR7RGzAQsJ6UcgxDiVMqzzm/0AGAbG+g6LGBRP8pSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T00:59:56Z"
    mac: ENC[AES256_GCM,data:vzi14QCKkV6eRTCNaSehnAP20xFB3vp75PH3jPQaUCGvfFRbPQxdR/C6w8MwqYWp2vNCXyjNf6W9WIcmYfREfY1wa1oYDDU26zvVSe7HH2offx1JoJsbm0Uz6QXovnb6EovyhEixtJMkpcWIKJJmbZ1DRlVQrVgMMhGuMa9Ufxo=,iv:hEEbwoyKJHkD8aCZcvrYN/f1rDmeNrdeE+wHuRU88Zg=,tag:jc7zVALCsaYQlJVtgJBEQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
