apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Fn50j6uQ2ambIdcfQ6sCgyHUI2+3T54YxlJnCu9BAIJE9IfflSMiuA==,iv:+UiKczXbkNSbL9TOItyM77rU5pVwWJSEIWdhoqSDzi4=,tag:8OLk69zYQ0G6u7hjXq2Agw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSi81RiswMkFTVmZhMDVU
            Y094L2l0bnJ1MUNwTndhelJ4RHdJT3N4cUFBCnNpRjQwdXVwaVNJcGxNVWI4QmtB
            Uy9mbVFXNVJUVzFDOEp0MXZ4SjVqRWsKLS0tIHlJcXZncTkwSkRvTlJJQjFBYkNT
            K3lLRWNPeC9GdUUrMENqd1QvcVFPeXcKyokzQNYMgQH2w56oc71x9o59nRF6L3AD
            pl3r+7zhrB1AwGVlxhIAL0i7bpUN7Zdh1wztfhLQsBvj2ETZF8xWOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T05:19:20Z"
    mac: ENC[AES256_GCM,data:9P+908GPVP9iq8nbUw7viaQ4kWKjYevlR3neu3eIzMXAX2LOUIWrxCdhWAj+zVDpNP5XIRO7ah/QxlLZZFNZJ7FUuhFMWGB/ysoq4Bo48RmifIzbbo14GoYTOpyH5JAfK094Tbu1Rh9UylivqaDXPCk/pRQRiiReeyNaY4FjmmE=,iv:+Kic6C6SQPrnSPiSbyGXet9cwQFXxR3bHU0McBAY05U=,tag:ddbQOnztnopXkqpwFWKfDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
