# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:hk/CIEPmQ6ogcZI/+Pabtn2OoQC+juzN5Lwt1LivP6qO2FY9ibRISzSURhsL2WfZXLffhWIuEaPXOmJWtvXORj4tlSymUxl4xswtpWxZetY9KXoUY7YDXh40UPHSRvNogIpzZCrbLjadOGX0wdT2egemTGhJIQRLz+JbgNu0DRrzhjJISDzyHV/8k867d42tLo9+CR8TcvueW3pgmq1ZGFWmCW5lcMGRJD6gRrbHWkopbJmdCmM4fYoaYR3wXna21GPYigQAH6PzmVePX/jxsImTvjypHAP25mqqpei6ffg4uL1TOsAgpprwCN8GpzdHR+LQDETQVm6C4chGwEGm/AoXKcedIWu8dLQKkaN4vRmotAN7k9WXmbZQkuy5Y8OLJb/iQ/a2n3r4QAFwNY7nt4lWdYxVFBLsBkR5chERXe3lOPH2AnYYGqm5nby94xtvSF94P6yc+sMlsAHvmpt5p4g19na40H3ypolujXfWYizzQrEwY0hehw/6XbzwPIO9rWnIhr/1wENAVArpFSeY63SGVEQIXYMvQGgTK+H4tSuaDgX2jox5ht5ETdN2BBwAbpB086ETPEEoTD1EGsuyGO0+CcU8uekvIByat6r8cUZhhIaJ/eNuAC6wnpRuIlBLtsT3A5tD9iexhNiQvZ+jI4+qaoyLOhWF2eldUiQB1Ng3ubINm7yLsCeoUg2fQg7FdEV8FVQnPFUGGMvNV30k56sxKjoTrW+rZmMjrP2WEoIbiLr7fceL4CJ+OFwXh9i5oS2YtmARudBX4+aLo8UCEwOZTZVjN/e3UbUYolpHrX19HvIkxfOykrHfQ3TF+u1XCbTX0U2joISN0xP/YEhfVD/IJJAF9MGST+BvqlJHe0xV7CYCljoyxj3nfbVplXb0XaEUtzdpcDrNl7B3oZv1fCtMUndhxfd6arNepz3DXPP/rlesc0ye+ioajzD1A67ABduv7PabrdIo5gkI0PXPyGdeBWivxM3K4wDB9qemX8pYWC5sYX6F5Y0fdho5fbfVEoVNldqIc8pj5gb/wjf+zQguJ2vZEHJdScLYqG8mwdW0RB3J5gXD0Dm2LqGRUpM3ay+OkFHjTCljW2vjhNwGXVj7tyEDCU/6aQxIsivQHl88NqyatN2LYMbNgILSa/qQU5bN/h71NaW5b6Mgr8wcQyDIEbQqZKXNoahYOyzSV5W49lyfDMXWrSXed+LzqwFK8C7+ONd+uTID3jNu8pjqrZnoglBTdMafnCKgILTRAmyc9CKqZN8wuf/bexRQZE9nPALFumreCWnHMMQkjKAXmnalFOUnhzrEdolMX9dyYdxz+yEQ8TA8YgKTHlDmfk131vINHwbzCkKKi875INTc97giE3wvHhoCVpIAIay50b+Q61FdK4p3p1sDIGdJOsgubtrsLtbacYXYRxta00wJXFfqYtF8DO2MMt6+g8sm7sY6sRj+4DijYwoxdEYwPLeJ0WLAKIj0LG0ibTaH7FFHtEyT6sYOiLvKaqPqtoxaZDNSFYw1YmJoN1NRtCvZ/QJSrtwQqyDRAGRbqfsi9ULHrSoy4+2H5HKwUIam4f9rAB15FvInHrEAFjLMdhi31N51Rq+t/vB3VweE0YjgmF2umsI7G3ouwyjR3FR4Grv6m0b0MgFNMtK33bk2dd6FLcNB5QoHGUvNCveRRtWsUkoZZ+CiadbTAIVTtzH+CedYY9C30Ozn40+5BUlxiFTLqmh3o2jnifWqu01e1EvNoWhgpwZVime7Q8Vzuo+0vXUSlIAsRqbdwoxnKGzeaFkDLsqn4bQVbiGHWxpMxP8s2NZxBalnzTqPgVjVb661kKwx4IIS2XlpsImgqYvl0WiectTTvkySeKZu4qiGNy6ZCSXw6B8aCIJL8zHYTeA1g5b2J4xNErJHgDPcQ5Vvpon8YmEycmuWLKAgCcNqQds=,iv:jlyB0L2jjyN4rzDeyq6lLGFgvYwviUUi+YqqAqmTY5M=,tag:jRw/gyZftRsDHr4qik3cyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z865mh6ngdtcmlnk84ryn2gt3kz722rj5unegslztrl2klmjy6s5cwm7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dURWclpId1g3bTVDMTVa
            ZzFpS3FkY2NFQzJEMFdGVWxUanZlbklQL2xZClp5bGdLZmliTTJxMG5QK1I2QitG
            eWo3UEJ0alEwVjFuSUQ5SmZZSDlzYTAKLS0tIFRmK2oxYlh1QWMzdzlxK2hPWVBG
            NUdBREUyRVpESVBOcWExTFJPQzJxWHMKPjh+9r3tITomc/r+cR18vzCig4iKWnAb
            h7MVktYITnlEEuGcO+RNnC+BPRrZv9URHOcCg55/KeoAstptYlACJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T19:38:49Z"
    mac: ENC[AES256_GCM,data:8LDtUqA6StI0D9r+xzWuxu/dZl4mj6yzbO5x6pH+SWVyTJAld+IvAV4sXCVSubbMCMEoX6EbPgh6bvbXD3jVrtM9g7tzbeDkb5Eppjk7/gKWc9Nf7b0xCZNWzJdweR6vi9iTyUKRCi8W+/v1KRsftEbV1IqqaBVAXejVUaSaM0Q=,iv:3N6FAZ0xpOf20MkQ5ceFzgdpNa1Dy0+1AjYoPGxYtPI=,tag:OfRkd96vFRYYd8FFjzLS5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:pC3Tob7PGyxD3IDpKeLn+HhtHVMkPLtr5gd/Q3yM8ideSIZTxM5lWB6u5raPIFdst7l/U+mMmSfgIs98QtSmRr+yXiWEjRiFEAwgMNZTljmPhEVewecuj/0l9ZZVRpOJ8gQrvLeir7QjkwGqiuNYBTnaHeQ5eU3TNGHTcZHR8zLyvRa95QYl+0E/FPOv0JuWQ4ozMFc6y3DmxVl0Fhi4HEAfFeSB6yAo+DnZ7+2ZVBHk49SzgNgWlWiKNQjbb4Q1jd0MDFQPVMx8JjJn5TroalzCF85FdJ7rq2eQtvmxhyQYO9/NFlM3CbTlc0qlT3VFXXcdR4J7od5BvrhmA7vV/cFJTH4VZqpEBrd1Uv2PBx1rJhBFM59cMQ1dT8PZniFWlbCIOP3G/nw4+u2B/2hJIW3js+E3GNPWkAGbkh/zZ21FW37orUoI6MoAmobzBbTsTp14JBH5BgZ71fC8hOT1wMm6A6MHZ+OUDdP/kO2RCDpapy/F6y9KUbsnFQtCv+A+B51limlCMsHOHKr/PnLw5ifPgndaebXj/gR3F1aFP3hrl4G7i6v9xP39240wZVpEn3MTiB61AhSuG8viKq/1gCLzg1ccL9vtALGvmnrjdktjyIN0ezSflqlUuk/v9aRaEtYEMz554p7BrbSgmQCX995SQKnfBnZ7mOW/O9Qp6gpCqMmsjTY029P1rBJ++3+P26BUJkwW0uYAZPAuDhBFNd/eUL2dhAefK1DkIlbhCLaIbYdd/TbmFxRhdXY9KSnFhXmaqQM+ALdgAKWqMztWeHzBT3ACr/j9+DErWktk4Bz25ePhOmIaR+RCxer6jNYJ/aUV+8/FMD77pBjfxucXN3qAhLcSsYXj+s9f+qDpiIQkiQVJWZOp4PGzXlx7RADo3+lzDAzH4JhIG42Vobdi+4dWdryTxG6c8a0=,iv:tbRTY1l4L/nQXP5d46pZ6a0UuyyTvlt+cDKjgHFovmE=,tag:IFz3Dyonn1z40mQHbpWwfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18z865mh6ngdtcmlnk84ryn2gt3kz722rj5unegslztrl2klmjy6s5cwm7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dURWclpId1g3bTVDMTVa
            ZzFpS3FkY2NFQzJEMFdGVWxUanZlbklQL2xZClp5bGdLZmliTTJxMG5QK1I2QitG
            eWo3UEJ0alEwVjFuSUQ5SmZZSDlzYTAKLS0tIFRmK2oxYlh1QWMzdzlxK2hPWVBG
            NUdBREUyRVpESVBOcWExTFJPQzJxWHMKPjh+9r3tITomc/r+cR18vzCig4iKWnAb
            h7MVktYITnlEEuGcO+RNnC+BPRrZv9URHOcCg55/KeoAstptYlACJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T19:38:49Z"
    mac: ENC[AES256_GCM,data:8LDtUqA6StI0D9r+xzWuxu/dZl4mj6yzbO5x6pH+SWVyTJAld+IvAV4sXCVSubbMCMEoX6EbPgh6bvbXD3jVrtM9g7tzbeDkb5Eppjk7/gKWc9Nf7b0xCZNWzJdweR6vi9iTyUKRCi8W+/v1KRsftEbV1IqqaBVAXejVUaSaM0Q=,iv:3N6FAZ0xpOf20MkQ5ceFzgdpNa1Dy0+1AjYoPGxYtPI=,tag:OfRkd96vFRYYd8FFjzLS5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
