# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:5fVZEoCVNMDAPqe+7ZYOBlAxbgloy8OknjYuxh/HYN/RxvA43/A3faz3h8k9lRrCPrFeayhAzEuPzLC9HNHQjpJT0uqHvq0oe6i03U6CDxSgknghTys6BJgYJsu7zRI6fHcKapMIDA1uhVWoPl0SP9CFKbs1Y0aSWPhc3cmlyvdEUgHvr/mYgpx90LcrM6CHxDg2Jn4ZfmOPC5L5skGB3zaV26bqAv6/BpbATY4pkTH3rfzuGEXATW/het3XTqJ/dVkJ7moGZNfvI4H2kqCvJEzWccZ1WMWMfAoSlOng64OpscOwoCcNB60K/NxGoz3Klo5xe9WwBCOvG9VaxbrILqBCb8MVPUdQtUeFD9eBrimsqoK2Mwey97i6QwdCJGC5MWsJ4sfdCR2GpY4Z2fU5M3U2TnVAxIL9ekJQ9A7KU06hn8xFhh8F4DGfv4KlrsPCqb1Gn7QTnSiNATwdr5Lg0sdRSs3T4g6qO/nbBrhscHdgUyQLldGpBp7BlSsuo5ZCYEX4YfR/eM05n/0FtVNwis4n7cY4Oa2hM+nAgVnNGlpC4esV7pQvEn27OQD5Xi0N9Snbpi8GYN7YIIvxFo7vMn3cFctiBQG4t+3bU4A0of1/fUK5UrO2mL4O2jguEQ+va8R+5n/7QTOyoaNZcuUWs7ErM4wkvE8ph9HEjQYFzBAHuKbzTcA3dp6PA08vLU7j7uYzKsEisNRC1yARwG66U4h+tUFc7NMe7RTz5uLh6ynoZJ/spsxJWcJTruptmrkirmMqkZZ4YRxp5bSNWtmiJISwoc8IvxkMAx1JkTV+8yVPzd6vIwXEB2kuCgLDWsk4qjHz30kLUz/tPUh7fXv1R/AZmAWvog6mxNuHlhXKEF1mULbqQFgF698ia/EtyUhaH9LkKM438epLJ71Hr3yAoEHFA71QsgJ7e1d0PC6FSk+8Z5BmoNZkTitw4l3IK0eQ+4tJAA+MK0+usfrC69Lb7+OkWYidnPF1Zn4PKmr/yir0cYcNeNyUDc+qGbtjRQ7lqbW2gHKKNRfgeeIsuH/+hZG+PqGXEARUseEVh6yNF0g0tXlSZhFh1m5vMG27siG02EH1+Zowu/CJFdtZpmCO5XmyAcdBTBdGmMQ7Rd314gjrqnnWOeIegoms8R2zkyRLuZmgIXMENE6k2zfcSB/+o+V10CMFxps08P7lasYdvydlXKCv7G9hHQNaYCJGFkh2zbIyxyWWJ/LJdgBzNJ2yFi6PHGxMDN+30hlIYMjhKoIyAefxs5Iw+cIFkCBIWEY//SDUg7583mwixkDuNgf9g2HZM+QvSp6RUgy6y+eBGLEkIY+xgCZK/ffDkcIPJDqPSPIMBgrCkagSzQw4oVZoxfY2heRyK1g6fBt8LgPEfu5G8IiKjUinHx8xls88Ld0bZgesWmDGjlWwKuVtP+PBtqNRAGZ0NkNdL3zYtcrkgAvW9jbEe0caCPKwKBOS622MqTbcE0vfhQXHjAtBy0VbSxEHxh3Baoy/WyBWP+Ab5w+b6U/3TgwOchtc/3WDMeNNqo1ujrYvZh/WmCxTSwD76s+GjpLM3i80LvBehtyAbHElTUHZYr9Wo9kHSuEldJNGcSDrqulZrvjWer2z+nMIfk7X1IRsz0qd3B6f7aWpOS0wBvHeqOJnz9KHyGCVruRtPMhjeC34wxXP5RRgkfu1ehcN7UquZn7VYOP+B7O/5Y3PSwsxSyxuhKLwfWSwLjXsTkoIwA38R3v4dSi8MM+NfSWFUvfW/VN8+kA+gWuk2bf8aexFvQXh+WsjEErg4LmxaqxdtbyFIDTEXyRbWrXEiCpzIKURop8CukoRuejskh+y+55Qd0IIx7VEtDOd3VKrq9H7TW10aHecJmtQJiTLj8Ndk1pCBnLhf9DUSeN8qy7esYZmbqRKxN3uSvCLxnO2I1Xa28j3xJUrLdI=,iv:wzcEInqSS+x7bAaff8d6S40Cg2/oxFAgeTK5tewbL8k=,tag:5Fnit+ZrYcYDSf61qwJPoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucWs0b2RzMkVtcFl2L3Z5
            aUxFaHgzV2hSWUZRWUxsTzBNNEVOUjR2NmpRClNjZ3F2TWtMNGc1N1hFZzRTUkh5
            VjVuMkZOY1JWK21EaDN6MWpMclFsK0EKLS0tIFdTUTN6UnVTRGYzTmNvYTRmQVhl
            MklzRGxnVGxkQ2ZJWCtoZDM1SURINjAKwSZcBtKEOZ4lcrc+R8Mf/Pj6iC+2rlEL
            j1pvpzojkmdRf+2ZGxPQV22kni8nkSTrboPoPfvXvl0Z/r5vLW1F4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T22:46:05Z"
    mac: ENC[AES256_GCM,data:5A1/8n+N7KJyT+hY7tFvSrAmfyExi3D+ZOiP4GQO15PClVJjtLsGzCwzy9mOVo77P5GjjIC8P7izKzSMbs3HOrrZV5Al83Z06x1kL4Py4o5nkn35hbjqKcEt0PH7idcmZe6nj30p8msutAnzZL4jC/euMNQ30cF6SnxLLGAarak=,iv:IQG7jWd2BTfzbFDSoOENsKGnLn3QUmjer6VLOYYs87k=,tag:rwDEz2lh/j8k2FAOzIybHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:UDYvQQbOF+BqssUD+7DS3Vzw2tsOl0f0eAUp31iI+L0q4nniHPi4LRITdggRmIXk2cgpDBKGHBBXHArdl2I9GrWqN7AshqsPSNPsfE4Dt0oSxlxKGbrsiLLh8GBjYoKpBj2xBpNhpvfU8SGIobuUGqGG5rS+BurVVVsOgV9VUwuTEbCCPRSDh3x4CLUlEdM+jLDrNhk0jSha5d/cmvnAeHzDw3P++QusED7ZWTWYdbk0royyZnIrA9btPkb8gCwbOYo4na0kBFZr64VJPhE2b7fEHuaSGkQth2z+bFxZTZOVrZU7gpaVk36UEDLq6ZZnmBw/yYMz/PNiYLipN4BUY1ndVn/CT9h7y+IUtjEHoHkVOitnCt6uVkNuAjLrOXYVRAH8RwTh4FODICFCC/2jB/weuV2MCwqECDrZQltMpJ6GbV6q/GHToNlEgn+QYpGAF1EANBAXBlAU31W2RcAA2ckxKQHKNwIKREPDI5J8antRseKT0uKNYCOZfTzgvON9MptiQzHkNeJxvnP9rIAD6AP89xHo5AtSiqph7eKQSD3yoJjpLq3HARU6HPlcDKFaZq7qs3tm5LQZC4WvBpEQ/sIxHnuRm/JPcGZR/MzXzHRSjo0dgrmse+QsKRDDgtBJ8F5FpL9tgFD2l9xWfmczWcZWxr3iBN5iTu3xOqCwF5xd8WRRzrOoRjKCJmQSWNS2IzWYxGmSQ/cGkWxuM6NYmD7+nq+YMqMTb47LDzjQcqqdrnwqVeI9OzmbdrVk8lXttDq2EK4puWaKItoZqGETRqjIzKQKMrBqi/XWFbS2p9qp0jCLnND9Wiwa+yzk2BW4ha0vLrDKcatveOR34ScYUYa17KvoYge1CjYcCdf9fsS2yA4SrqOwXQAmmmOGhIKtHV/VEFnl1PfHrM6ilcWyb0UFPL3sJnHKfkA=,iv:1nBpiYe+J47K3wpbvhEVYtNG/LvvvuxZH/G222PT7GY=,tag:uUIoCX3z+mcGB12GzAi9iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucWs0b2RzMkVtcFl2L3Z5
            aUxFaHgzV2hSWUZRWUxsTzBNNEVOUjR2NmpRClNjZ3F2TWtMNGc1N1hFZzRTUkh5
            VjVuMkZOY1JWK21EaDN6MWpMclFsK0EKLS0tIFdTUTN6UnVTRGYzTmNvYTRmQVhl
            MklzRGxnVGxkQ2ZJWCtoZDM1SURINjAKwSZcBtKEOZ4lcrc+R8Mf/Pj6iC+2rlEL
            j1pvpzojkmdRf+2ZGxPQV22kni8nkSTrboPoPfvXvl0Z/r5vLW1F4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T22:46:05Z"
    mac: ENC[AES256_GCM,data:5A1/8n+N7KJyT+hY7tFvSrAmfyExi3D+ZOiP4GQO15PClVJjtLsGzCwzy9mOVo77P5GjjIC8P7izKzSMbs3HOrrZV5Al83Z06x1kL4Py4o5nkn35hbjqKcEt0PH7idcmZe6nj30p8msutAnzZL4jC/euMNQ30cF6SnxLLGAarak=,iv:IQG7jWd2BTfzbFDSoOENsKGnLn3QUmjer6VLOYYs87k=,tag:rwDEz2lh/j8k2FAOzIybHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
