# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:+65nZEpUhrbnHsJaDmZTFC6esEgSBUxepibtUqLGm09Gwfhe87Bs9en3Qhgka7W2bDooAVOUaDcwQJ2RWUJDBAmcVgcLcj7TrnB9GAUD1YVfZJ0L1qb5eaHQc/3oklUrsZDOW+qHBz2n0vFlhrOGhSZm/FvVe/dfIj/P0FqdvU/ynSm2SrXmBzBHc8Unfw1RSWBS6Gr52JpJjBFGy9fhT6U7B5W0Zlf0Niew+0MFMEwzuyW7sM5/2B1xUvkguW5nD6x2NPtA+OWw21Kwu3mDwQ+hdNDHpT/+VLrR2RHc+h3wYwGmQNdOse0EDaP6mu8CYyxCyvupDoWeBQMkH8hOhq/93ZJQsElikLRP6fywBCvvmkVhxBuySgJHn0PJ6piKXEUHmZEXXFqcmQ/8juRmr+/iU5Y+9/lpD21ydlxkDyAxbA9AIb5IpRGh9Ekg//jI8T5zw411rHlXvwenMObm/46y8TwafnnkCHzIoU2qftMnBER85yNJsfpOdduT4OADMMNcJ6Fm+casoqA7y7s9EC/6/ghx7FNJtjBLyb9t8LjzU7HL8suhUO+3mFZOkqk4t92Fxm4aBd9zcv3jlhjdTiYVP+6pCy6QqoAZO42iyCEmlvYqha+5OzCh/VHr+YToJS94v+hid6LSpwsyhGwRu4j8S4wp3ZbUUn1AxxdNQMCA39C4DqlXLJGHaOPBrNQiGA/AdTKcw8Fziq9zHnGDv9bXZX8sH+npXMIO9J8Ggqspo3Wz/kHb6KD3SMpB3AcjkUcUiSSSK/YiK5tEeqLx2QplZVBis78PwSSJx7i3vWlyAHf/x8Vl0Tk+anBRtigg9XJgiXZWSS/eN4OtweBDNYIfqFSwY6Dn3worMK2yVr66zFu/rLbve4j2Yij+2sClGxiuEtq8Xon5a9OlxZPwcTsGlUfcUvWfhq05UhznnXO1p79y6q4NDhbfDBajA19JpsGwhnY/xnjv1w2y7qwdc0nljY5ryPYoLS1QJzLZrSiQFlpE1Bod8RHSZrgpTucENj2M8Mnu2M0XfAcxEnGY5aZFZiqxOdygu3DmXBUVDQA0S8upw1HsaRSN7+yfs6Cfcu+x+CDQXF3Vc7eHjf+grJfRLL/hTJSedDmOD/yD24kE7ny0/80BudTtXsOMrY8qWAIbgwDPXDnLi8KoxVXArgc1BMd6fltpCYVR0DrGxKb6txPLVTbp472x6AWWWFobKyGFP6Po3iPdmv9Vu+re7EtWwwMI5TVSL0/mRXhVdQBAchp0XuGXlsZFv3NOsDbs7f5CEWp7bgtfaVDgEicOb41DP9VPUya8eAdkBA5G5mcNyT97VGqWViGxKs+YSNKdi0NhZ4TaSqFDNgX7UeJ2PqrZEuCVrqEs9vSxPMQ/5bESMz7BfOBR5FFcfRZWpTqDFh3GbL+Lz3g+ep6nvc+og8G6PKsJiImCBVkfQfyYbs0kO/Ykx/s0Egi0jyq3XI0XT2zEjiEZoATzdbxvK0gd6Rbk8tRb9z+mqusqnl++ApsKYm5Bi3WdP9DobJdQ4edrPBnwJIDFfDc0J1Yl2o+mAbKyf6g5SZDSpuMG8VkAipYtEGuuDCH/vpvnO3rK0trStD4wfLe2g1Wxfz3ow346cWuzR7vVQcoaBNkReERg7nTaq6kIVwWL3j2H0xZRgbvDeNIH3C4zPxBxLaZ7xedrqVhpSIwsAt2LtM8S3+mb/tTPg6wOE2OXVIbme7CAJTG/PZZj3NOlICEj9REiLTnReoi9ZU2XXVJ7zLjnkOZ7yttCwGXt6LjQTxBhNNA1l4EjrXC2Mke9Tc+FET4SnhwKZTk5SgDIO2OoYjMOslT513F/ZjOi79dahW1iFPvIuugIxMGfn4inv9TOS71TlJZsg2v/scmJgh8C9csVvvgOYO2v2GCqXf2ZxWsxocTiupr1PMXzxMtYXvgxJvM=,iv:tCnih5wPoCqLn1OPJfoGG6ZW4wNdr0LjK95xqFSt6Mk=,tag:q4EyO1sLSPPhEbM9wK40iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWZFU1lza1hXYk5xOU4r
            cFlkN1B2TUV0SU85QkJrZmF4dHJOMG1hOFZzCnl6eWNBOVIrTkJzL3dKeW9aSU5i
            TFFLWTQ1ZFRIcGZ4ZjBHeEZjd1BrZlEKLS0tIFpPUE02djlFdmMrUWJqTGRObytN
            Z2JzeGUrUGJGQmNjWmFQWHY2NHRza1UKxguOLqem2FR8+wSu8RaNpFNo8BU9yA9b
            XEWneOCVGASrOSBn87Jx6kiSGM244NvqmmnJYvgNcaaCokd0NRidfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T07:04:17Z"
    mac: ENC[AES256_GCM,data:fb9VCcNymkz9S7US8noTo+Rv5AiezGvdYyvKycQSvnEVUgPN+ogsBBw6qhIYHu89HW7Oe2lQu7Wey5NmUdolhMup5OmYSed5dQSL+DYDPRcYMWX41ivg6HcuH7DKsMSmvBqq27gP3qhuPS8qMS65M9kyR7sf82BMLwmhpNHLKNQ=,iv:d/dbiIgyAFCSdnJWDTAX4h0EBrnbTVBZ8Yr5M5QbTis=,tag:ph16zNnZaHTcdYkZsrzuCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: external-secrets
stringData:
    token: ENC[AES256_GCM,data:+JEnIosZXL2+pUleeP+U8FwvdA+qqUbDqOSVYxN1R9BdsyIXHQ0UTO+1sf1AHalhdGpRmTxHJ009iVKyYH6BIkFs4VTCyYVJ9gSooSvgKvulWgZux21CYZKplMVQmma/E0xx8QgE3A+EZGCc7M1/v9jefwpjebrnEQazzFn0QHTwOxp1qDU0h77dw3I938AGF9acCP1I82TwvtpjQLQ8xYAYYW07r32lXRpwCMbVeBKmRbayJSw75t0HJXnGpd0LpaR2ccL4yeH/CxYh8UTIOPpRF2VkKdsbfhC6P5QfjAwFDdH9w60jNu5V9wFOZk6e3eQyl8T52pBkfxya7LrDC34ePcSWRTAEDijeDPaL4u1tjg4QC08zZPLbcCCr5vk8Mi95RNwrCefhFI9D/bK9QbU98WzxD6KBSrjk4lMlER6osvdyUT8e1qSfMYMCrz2Tv3mpwy2kpo53whRNRdU+r0WDCn4Ntdp6xJxULlbLEfzQw9ax0G7JClaWhM1GCT7mZCDnN4h/pbty99A+TNu+a2cn38fPPXMSPKfz0LE3R+TUJou5eUqBIhYAiYw02eVA+mr/0doGjyt3vxXsiJLoGwjqAI6zmcAMLmoVlkru0h8MZvEvSPubLLkT2Pu1vuVAgmnazR0AQ0SIjnu9BmeD4PUfKoiNrZJPu648yYxUfpvlD2mYthPGFPIKaNdUAAKp0A5u/hyuHlO7qfS1k8kqORqrqyWNbeFX217oR/g8wTrYzUAQUyZ3yHrKMCM8HCkgVryyZFoFYCkYE5Qwa9eP5rvBOW6b0CftuemP+oHzROUAk9K3f6JNm8Ln+v2OtnClBw5f767qZ8zN/osh/KyTlYc1LDnHvB9Fu+glG2EMvegGUD6cKJcXJGOFtv1JTGEC4ARpo6LnPQ/Ktu+Rbc8kJUz7z28WwZ6P8SI=,iv:ZTOhLNclxGmtU7FVkoTv0cKLrYVb/ncBJB0owHM01CU=,tag:LsM182a7pk4L66EEngPxTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWZFU1lza1hXYk5xOU4r
            cFlkN1B2TUV0SU85QkJrZmF4dHJOMG1hOFZzCnl6eWNBOVIrTkJzL3dKeW9aSU5i
            TFFLWTQ1ZFRIcGZ4ZjBHeEZjd1BrZlEKLS0tIFpPUE02djlFdmMrUWJqTGRObytN
            Z2JzeGUrUGJGQmNjWmFQWHY2NHRza1UKxguOLqem2FR8+wSu8RaNpFNo8BU9yA9b
            XEWneOCVGASrOSBn87Jx6kiSGM244NvqmmnJYvgNcaaCokd0NRidfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T07:04:17Z"
    mac: ENC[AES256_GCM,data:fb9VCcNymkz9S7US8noTo+Rv5AiezGvdYyvKycQSvnEVUgPN+ogsBBw6qhIYHu89HW7Oe2lQu7Wey5NmUdolhMup5OmYSed5dQSL+DYDPRcYMWX41ivg6HcuH7DKsMSmvBqq27gP3qhuPS8qMS65M9kyR7sf82BMLwmhpNHLKNQ=,iv:d/dbiIgyAFCSdnJWDTAX4h0EBrnbTVBZ8Yr5M5QbTis=,tag:ph16zNnZaHTcdYkZsrzuCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
