apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:OQ4zevbqf2vgufsuF3LFsm0GdPB8OPFnGYzgAy/80WLW6tuIMjvz6Khlu5KOPaOVyL2oLi1T5c+prFYyyXGguPk0G3vKTsA+P4bmO5jqsukQhXS4zhkf/eRSDBa7wA==,iv:H/mYlQdtVbD6hNHIpLETOdNoqBpehZwHJTOz9lH442k=,tag:/y50EIetKedZAjCQEEOLmA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1oqf4XQENqrXsOM=,iv:rPx2N9vDOKsgG0hivKzqzt/27OaKhaW/NSZJIXq0VaQ=,tag:7A9kLGM67pkJy/bo0Y5Bdw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sCvtyqx4bYdiHJeZKVin3w==,iv:AxPXGToiSJVnc1cY4h/Mda2XJzbikRD37Rm/jb4aK54=,tag:aC+av4kCwpXOhD2ONvWcgw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tC1J6rNK6DoBqCH6TaYynaU9QSwyqWjDCvd9+m0ipDlkhP9N,iv:jbwfk5INehl2CL1AqTf+c0EC4aC7RfBZmbr/nUvpmVI=,tag:2sI+r7+XCfElRSInhtFUiQ==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:fPj8lYNK84HllSHI,iv:kCgY64xdpQxR+hdIoC65cKokohiGFiSKh6VD0cy51y0=,tag:GvJFjg+I1BMA7GLHXy2GPQ==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:Y4Z7U0mhxq/niA==,iv:Hjrxio8Lq6nNYpcLo1UmXphK8X/PfcGJ9rFbJtbQVrg=,tag:BRHyb1mDORuwlgfFm5WO7w==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:hOzgWMHegHuIYw==,iv:Io1LSoSh7n9rjEYUqb0zotoibk64mGoU+G6fpciWQSk=,tag:DaAT2s1gucBgrJOTvkxeIQ==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:U1NqwkMxb2CbDw==,iv:znnDnGGI8OTdcyHHKq3hqz9BfkFIVE1I6dVb4LiAiNM=,tag:4GYQqs+CvBcIEsEDIU4N8Q==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:pxddKm3moZgt7VXf0rbC1ck9GT+Hu9oJyOD5,iv:VuANXwN9C6XwIqSbsA33bzmWYgnSBI5lgqCyiWFvdcE=,tag:M6ZzKIH6B0HaaDidy3iAbA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:hGmMSVnlfplGymaeJwOH3w==,iv:okDSurp0fgAM6VhJNDbju0fkBtBJSNN8cUmpjfzTlaM=,tag:gd5uYur9q2b+5Wyc3ogJ7Q==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:Fxq3ShznhzD7x1M=,iv:GJtnMFZyOwXVvcM73RxJN1zJcF2hv+Sdlq07btSgN7g=,tag:4joqeO7LTW3nrVAcJzCLhg==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:73rTp1OSQ905XjB/MP61DwE=,iv:wZt6YpBUVv91PP7hRRUeLyT3aLInVaROle72ueAK6n8=,tag:XmQkHzHYMWkclQJ5ZFEdGg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:g1pUFAoqHAnAsL1Uroc=,iv:YmPQwjZVTSeq5sU61Z9npKRpAKTKoehJk5tGTwZYw9c=,tag:EKF/sXtYGp4FCSJntah7GA==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:p/7dREYuGpACSCvNQTU=,iv:kPNi6zmytusW3gkfoIhMOL5JC9mpP8CiHVuMeqNYsUE=,tag:+hHl03Qe18oUdzc5gH6y6w==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:GsaRThc7vMvvfQP30Mg=,iv:ioDbuuuKOOLBn5n9N7Nblzw/BgRX+7JXTojWwgFrV3g=,tag:+8CDbi0HQhblKVb8hjg3kw==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:L+blqHyYSjD80M0N4musKV7JTA==,iv:3K2rLxRtNxNK44u1EFN0zaCijb/jop1mqqRp6MetwMY=,tag:KCnqrP0OapOcUvyIwthwuA==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:KF2qVRZZUcpd0b8Cxwjz2HxCYQ==,iv:E8L+STD5Iw3Y4JXL8uSCxf73Zdu13IVe9VGSuiHKRGU=,tag:FkUnl+VuzRnMSfYnpMb68Q==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:1/c2et5MAVWTASfTs/yQOqapDnqHqRA=,iv:g+My96pR76q+BgnW7Rrihs4s9sKVontCfqfCNMLIYqE=,tag:EPXIwslDX+zQzYxuGHKqaQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:cjnyNpgH5eY5IARWwBPNSQ==,iv:d4bCgAzCl2MAYkEsHwKLPpGX89ao5vdNeAPDz/Gho8o=,tag:4C2KdagEbsv2F4mOCcnHtg==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:4No8EmbdyD/j/cdHMzhXrbIOZi6rvkRjl5UaCsHE6zEyzwQ=,iv:eqo87WEYBE3lBWxxjJBJFITeQmATeGqkr+QeiaX9/ew=,tag:XTnzacWk9OhT5Ro53V6ijQ==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:6ABXRlMSVAP06p9l,iv:E37IhrKCAWzEgcL4e1XYTcGlfXMMWl2Ch548HnfKJw0=,tag:5V+vaB4/VUhTNIUsAYCy2g==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:E+fQM6zCiMn/Yl+7,iv:QP/1v0W3RCvycvNeVeFmH2akXy5etZ18jVbgt4b4ItY=,tag:mJIk98OwQuHUMR1kEd5Waw==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:xEtiukM=,iv:lk5KqQO5gNVVzt8VUxccJkHYHNr/RkZF7sCAYIA1f/s=,tag:ou5n3uDHbR74+i/H26MBPA==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:RZCghiOLMrZToQ==,iv:L8CA22UQUI1Y2MXt3pVak83PxF4gw1DVV0ReEXWAS5Y=,tag:n7Py1zhKum568A731+onmg==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:BFA+grpjEzCDAjFc/ko=,iv:j/84gg8qV2YH1oykWOdSeR2pDlGQhlO4H7CLAf4Xk7A=,tag:4UVt8hrOewDp5pPLx52JfA==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:LCvrRdjPX0c=,iv:I1iwqkdZ1dJH7EFf/IwwfcVP77UCRg4yGHsm3IA4wH8=,tag:RpmmUipAFo8F4ryyXG2XKw==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:Gte4jqI=,iv:QH9lkgzzQjYW99B7TMHurB7syOicX331Xd0cdsGBbeI=,tag:QUhYhGRYlNC9FBTONUpPlQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:4Vc7YUDojWw=,iv:Dfkd1Vn1y2mR8+zoWeKh06ykuKLkn06pExE25gU//2Q=,tag:2DvibFmrRHlK77JEM8ApsA==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:HlkEOAxXl0MgVEDofxM=,iv:Mg9D+IHaLQpItpbNglYNRVfp6X2QBkcTbJUcg7qgnn4=,tag:hD8BbtOubfHPd2W/vAa0qQ==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:8bq59qV7FFE=,iv:rUsX7DcE11AXt0mi+qSZ0peDsjUCHjx0kFgIxtpoex8=,tag:NgUsoJstUorr+Gmu08HZFA==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:csDo9/tPvgQ=,iv:XMqfO/HJ4zH/brB8AqVX45dXRvSEP2AVFAgw97PDHoo=,tag:h6zUytCTQpeqwo37frwKqA==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:Tih4ZiLG++A=,iv:dHDCgZEK5W2Sr8S8HXxu5p1U6zmWmNmK+tRoZYrcM9k=,tag:5PDZ1VLKGMK6Svfk7iksNA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ymlRkCJNGlzN08wg1OZY5jvV/8hvqyZ+sZ8=,iv:/u/SpZFYMEhKxVsdwqyUq6Jfl6RMdfzs0035ipNMnFQ=,tag:2xEUflJTTgH0mRXtrspmJQ==,type:str]
    TZ: ENC[AES256_GCM,data:Jt7/iYPhJVPQVTv5VwlSJ+2O8Ds=,iv:TDPgrMWgSKvyNpIwakfM7s5SEh1aXy4JV6hyRU0l/0g=,tag:C32lvqbG/b92i7RQuz0WQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:HkWPEJg7fw8DhdOdIt0PMhkPE6YatkasGDjayogxkmvUR15fSzDuoPhd+GFqZGykc+dOqPk=,iv:GgsT8gnNW2jd2c1bbOaR+bzBrnCpltZ4ROYEdFuuBhU=,tag:oeF0PNZSaW+X5Vf4w4fWgw==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:gifK9qpLYMzYkQ==,iv:HH3/fkR/5ADIKCsVPCF++LXthoItxFCVpv+3vyujqKc=,tag:r5ea5bNX4zUBvoYdHjOBhg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:TQQIVrQBCQ==,iv:t5paGx1Z3pyF4znXmLCqTgccrpfh11nXct+WDlSEmbU=,tag:NDg2/vXkBkys86l5GgLTzw==,type:str]
    VNC_USER: ENC[AES256_GCM,data:pA09nTE=,iv:nqytGupaUdLSAnlS+tJD0DB3xa5ygQGbPbolgvAq0/Q=,tag:/Ap+jdDQ7hbJ6Ntzw7eBPg==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:fwLHmPztRF4=,iv:h6/vezvxHtn1FVJelbcivCxzmgDPAR/6huzP4qDTby0=,tag:BMuFn1RR5MyC8AS2M73SOQ==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:G2sMZVMvpFk=,iv:CMkkGh98HpgVtwgpeDgjBb6Fhd/8etGeXxUrutB6x4I=,tag:f7eCAe98Kpwqx5J5DHwsgw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:zWTVE6hkQ8s=,iv:4E6tJiZV+7lAFIlcb3JUsxULn5q2u7X3Sk6BqCjNhHY=,tag:ZHhAVZhWAwDvreScPVbEIg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:hhO5jrc=,iv:5i35i+0wJlTEW6CGZ3IsQvuYG7SXzc/dVPXvkpry8XQ=,tag:Ff/CekRy7ngqKvIOK+wisQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:XKt9q4fhbOI=,iv:icazc4tGT5atmN1n7jMUo0uH2qjJSSH410IrO2epT4Y=,tag:3ipldrHxh+iWtMVBfzCkgg==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:RPzefToG+GyyzQ==,iv:5LmMMiNKZMoo3f5IZD1Vbv2gW6TtHsUz4ETMtUboQS4=,tag:FQadizX3hmolTTHnT1/Grg==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:Eh0OEhenf/nkPAWMEKSXjg==,iv:rjJVx1r/Y8Y0/H84n+GtHy4l4KeLV2bnh803Lz9YjRQ=,tag:aXW6FJKJ3rc3XzAHo96mXg==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:GlKxszZJRhM=,iv:ZaNtfjGjDCK8afQnLj10JI0vaVmaL1bB9mke4svMp40=,tag:H14BHaoaQHeeJ9E0zXQhXA==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:PQrUHx0ICajiEdfWWqoVTw==,iv:9DkDVfQeEfHJssnpLeyCA2Boo1vWwz+pSMO3H5ay82w=,tag:SMSpAdhgRjTM3AM6hchzGQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:fLqm2dJR2eK7WME=,iv:2zM2l/pTPixf59MGuevqgm6q5ZdnC8Jiwo5qM/HMSM0=,tag:mhY1FlUrICrJv34LRBfzPQ==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1O1TXQCluA1YLImTAGVUQpa8DNsCc2HTqpo=,iv:DWGdpFfqDvskbmowl8QDBqL3SVwZH0B4WB3lgwMhZzE=,tag:LiHCkYsoomvXFSBdrJpoyw==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:5jgIIjaG45JSYuGK0pvsd2sJWDdkmOZRWfQ=,iv:LpvU8gLX+jlxWXCoWcpdna5Iw0tjEzVbS2tq3zE1+Wc=,tag:OYq8xjtbabM12mOHsY1ayQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:QnaP/DhVFw==,iv:41jJlgo/Ab+lGJc3Iv01bgJRgq+g/LlqDF3KBZqpCok=,tag:f8H5h6fmu7f3bzuzVzM10Q==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:b0Fq5XM6Ff4q+Z3pWrufK8c6xoLwxGAld8U=,iv:tJvBCXs9kzbubzvcQn8RhXvtjAlo0xwHGTttR/+Rl6Y=,tag:cRnc7FKdY+Uo49HX0mW6LA==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:gkNvVwpp5e+Y4k84vR5vkysKUtZaLZVO97HPLiqBArk=,iv:GFf7ab4xQXeULRqyrwRdDIHFHPJPqnGG/yvCWq7tDjU=,tag:C1uC/Dm0NXCTRMUrZU3nMw==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:QRYRjPtUNSs=,iv:LsItKskH0Z/XU4cL6tg8SMdk6wgIyjR2ocuLHodjawM=,tag:1tVm3f7OZXDtBIdoxkzcPg==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:NnTJBE2ijqk=,iv:hHTBh+E8/MhU4ASb6ek0MSiLtDs/vSZ5IsjV/htFNBs=,tag:e9mJfJrkYdpgSQ29LixQ5w==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:C9I3MEm9O+RCAkM=,iv:lPc3M78iKnF+G/D+erTAVSVMOgQqZKoCirDn0pPeD6Y=,tag:YeXxVjgoZxYBqMLzx23A+Q==,type:str]
    QNAP: ENC[AES256_GCM,data:FnavqH6p08JK8aY=,iv:7qWWV9ust6QEx0BZxzyG66U/VBb7ngHGSzyxTqKNW/c=,tag:NIZjFd1s37iTJ2f1MMOKnA==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:yvPZXQ==,iv:GhJhubUoW0qfWRtIUkPrOoB5Ekba2IND84uds1RJTo4=,tag:emw6jdy1GIW5kAnWYwfgOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cHdJcCtiQUlPc3E3NkVn
            T292enZLSEJuZXlpMCtpWFZqQ3ZlcWh2REhnCnh6TytrUTZWMVhBOG4rSkIzSHly
            VTVKNjRXdGVqZ2dZbElESnQ4VEtRWXMKLS0tIEdWZGE4ME1zOGhHbWJiOVk5cUls
            YU1lclVldndHNnNOc2F0WkczbUxLS28KgXCfb9ODErCeTsYZNt2C9UmaL8dFHb+X
            Zl1fFmt1CdUnkuq+wjwAUy7oXwRY7l/S1spFeBekau90xXK8wJtpbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T21:38:52Z"
    mac: ENC[AES256_GCM,data:4OX6BZgzoOEnCdlDxE6/0wbwZg9rd3Z+NXvZJcttJd3FL26zSNtng3IyAa+JnCkVnVfCuawqW1ePmSP3BOX1PbzoxC8y8td3yL/d6n5on3ISdArBPPJD28NhN/JutK3qsjtakqKqLUh05U92O2c+JYpxfGT4d8TTt5Yc7n81Xbc=,iv:Hc/n9lNPL37D2LNpVNQ8viFYvhY9qBiZO1e4RApQthg=,tag:BSMyY3ht0LoHLiAosDTb3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
