apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Ivk6aZsKCVRl0CC01/lCF03Q3jSlIN4aX/u2FYWhYChBpYWE7DrqV3h0dY/xpeO788DPkwaMGDQ3dbpwLXZ3L9tXN05WsVD/ea8JMOq7Cw8WTd3/9S5v2pmtPPh2HA==,iv:M6P0WFd9VrOltFcYKi5Yhtrdro+m6NaHEaHmkjfNI84=,tag:6CHowZXgO/CUDZDz1jvh4g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IYMdNDVWWCsuXGU=,iv:f6sZkzHNeMWSSAOpE2RjOajDYdi+mzjF5Ji/xn+xcRM=,tag:QXMJbnDLJNgTHXl7jpIL6A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZFA2bEwkA+UzTfNAfmZiiw==,iv:ARPAoax9bX88eXbUzf+XuSNOHhZsBakjM3q64U0ZVII=,tag:44tBx10xcEg4eycMTEteoQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:YvHotPZdZXPRiHoDxbc9BF+IUta+/PX0cm7nx5KNmIxY0Pli,iv:N0AZdLcRXTH0SZ4CVUvf0QAfjwFG1ty1mB/4OTeoI+w=,tag:gs3FV5LtHKcif8gdhYln8w==,type:str]
    SECRET_DOMAIN_LOCAL: ENC[AES256_GCM,data:HYiGXRN85dkvQ+1y,iv:Q5Z1VQinJFbG12BIT77QydBb//wZH/GAJUHRhC53kBw=,tag:/3DKJYGQXG7+hlKsghLv+w==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:tiTqnq82doe5Rg==,iv:wiRlSUrHL7KmL7sIYPNJOV6BIBI6ec2jmTUvcK5AGYg=,tag:ImLgA2ibehNzEseGj+u52A==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:J2+jlm6WTVUEyQ==,iv:srZaFFEYeqljSVx7NFgPS5J4nAcEc4cRAnWe34gaHHs=,tag:k4963Psy9HIUrD44+VQ6Sg==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:UjMspmVs89S1nw==,iv:vtGwtrz5zN6RuSjuPWdlBZYuLbKCgwjOCJ7bO5J7OHE=,tag:t+Fa55si+v+KB4p2YgDiUw==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:yd2QnB7nJiOJJuAzLlsWSDnJjEg0I4/s6Kqf,iv:4dvb0tEA8mYFKYOh0P5YhxFPiJeXbR2g5mH61QLm/HQ=,tag:zMq3Ya1slc4op83mkhwzJQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:84n8Us/M/gX385SGiBSwBQ==,iv:eDW1NRCRxc3n5dSoRvsP4G3gO30AMufmA5gKoO4hjZE=,tag:cW0Ppo7X58Hh/CEjkZa0bQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:OTwUuhhPHNzn43U=,iv:67xwFbeu+1M/KHbUWKgwxEtVL/bkiL4wDk0WX1SHSQ4=,tag:WagqBZdDDj/T2H3k0xomdA==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:AIQ51JIh7DPGP7mO1lUABHM=,iv:FC8fC8Otwa8rdb0/jhGfIP08DaWRr0q3mkOXiuXqPmE=,tag:eOH2HjIUdqgLHt/b6lH9eg==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:BvneJttwlnc2/9tT7Y0=,iv:T5WgS8zIqjDsz62MyV9SewbnvL3KKE8CSJg6J9DETKw=,tag:HkVsr+mpsJn0aGtJgfkvtw==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:aN2juwTmA7AvGC9tTXA=,iv:fmZ5Kv/ZI35TzJnkt1WwVszTx0SQbcD/0Z044YYMxpU=,tag:M+XkQ4mVnraq4fViWKnhWw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:ZTsqOAHQ94bVsC7RTtI=,iv:kHl5uQBqMXvNK5WvYanlbZtv/sHmcrHFCEiVqGEDLJI=,tag:WXyBiN+G2ywKMfQR/2SRyw==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:NkPDt17lETq5U5nax34efaT7Qw==,iv:R3TvZPj4a70No1Q/YHQzezDP4MMNCF+fJyuaY9TCCCs=,tag:jES9N9FcQpgHPlDEkGj7mg==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:1cX4QtHr7FQWPeE+P/jEXmzqCg==,iv:MS1IOb1iy0Oc66mxw0ccLPJlX7sJwPvlMOeQUboPbi0=,tag:dsuzEsV9XnkladpQwVoRvw==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:LN2JpQF2ghiZ+whsf+/scRTmaC8yCdI=,iv:DzZ15l7AZli9+zA4WfqN1QiZCSk6LENkxwm/Ka/AK0o=,tag:03GoaQYUnfls3iDC1nIqvg==,type:str]
    EMAIL: ENC[AES256_GCM,data:vAycfBqxfMdDTAU/p+V//A==,iv:KujIXqDcGspSVpbzInTn6t9xrjREjz4d78b+WR9QH0w=,tag:uDNcC+SJkEgf5i89Sx5J+Q==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:34NfWuDZlCK4oWN+en11EI1eheFFVkCtfcB5GjtT/Y3ipT0=,iv:etRbSmTookLbt+BY+CnLYWu/x13VpmZYSB++bCwy/Go=,tag:3lEraeJ4bmXQ+is4eTFF/Q==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:kimLVGtDjh+b+V+N,iv:aHR/ktEmeW8qTIQ/t9QiD83SpMBvnoQ26ItqmPWeR/Q=,tag:zDjqajK3AxFe/cCI4fpM5w==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:lS5ygBK+tw2/cqx/,iv:RhPlkEoxcXxPVHJB/PRhFnRrHjiMevLMKUS1Dpr5E8E=,tag:q1ctVCah7jbCFGuy79dieg==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:ZYYexgQ=,iv:8Ce52D68g4hyQrCIfvUYZeI5TBwRD1pdn/JvgMIUyJI=,tag:zDTngfUQRZ6bqNFByTx3pg==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:bxFZZsisYwBNRg==,iv:ggAsgo3rhqxE5TRzfKdV8tQe5poswx68j+OUSgNtZw0=,tag:JOPigOeT9evwrr38fDb9eQ==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:T4oeIOvvaEH46e+Gpho=,iv:UbHnBkHNF646qTB76d//JFkbUATEjeW6oCNZWOej17k=,tag:TztFKKFRDIV8pyBrmqdL1g==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:u0eBFRoktIU=,iv:YBM0SozXQdq74Kn26y6yhejR25Le49gmlY3rpsJHGbg=,tag:6R+gQlO4NLNQp74DdCJnQQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:i4+LNmU=,iv:YZclU4RXU6j0cVDGgKSRCIzEBLh/MMOMwKJTDI2f0e0=,tag:GC+ffPtFzpVzGGsOwTDc1Q==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:sWH6kYjSeDY=,iv:jMC8qJQxHNKOwelosRgdJBLegTKuySbNFyVznMy159g=,tag:En94qQFds7XhB4RgfM/DGQ==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:sQiCJd+kD2bAVl5KZ8g=,iv:fN74x1i7J3wcgMAkwd+7hDEUG1zP3NAXJgModTl3A0Q=,tag:GbJTOTXhBHls+TSqPd+cZg==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:+L9wJa63kZk=,iv:7wvOVCX3ZR6v3QKcgPNzas0kERev+6qRq1DQ2AOAzdM=,tag:ntkvq7nu6Mz0KkijLxq+Yw==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:0k/zjFsUOG8=,iv:GRYPc31ehlryFtNiaBUu76nuPJfD6TsNhCsX7JMXqxY=,tag:9Udy5LC8wMtlhNbpa0t3ew==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:R7nIsL+tChM=,iv:n6ibwQg9kNUm1A+9/WwD5SkaeTeS/SK8sVPr2AIrfYY=,tag:QcrSoY0eYF0q68+iNUauuQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FK1lxQluuoJ+ITbw1YHRtCp8BLzdIs4AnOw=,iv:hCxoB0FLKyLJ8YPrHZl1wGJLA2ThzZgs5gqb7BaG+Bw=,tag:NnAp7bHt817/zW5JdnugOA==,type:str]
    TZ: ENC[AES256_GCM,data:1dUNVZbiOc8OlJO52IWUvVZehJI=,iv:F3zpkGUWZBDI6uGrhM1HtTv9KGp3uavUfugyuywMfyM=,tag:dHtBuRXQzReXzLcq/spdXg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:1QgdqC9aiVV/To0N9DU3ypv+JiSae1qYaYwEpt2xmZJdB8U7RWRPs8+u3O0cKTTXEhxBHFo=,iv:pmsiXW+VzXJdQWJxeBewt7VdtR9dIvru2oSKUeQKRGw=,tag:7DL8OOiq16MMmEf66pfgaA==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:LqHP6YXy8xybXw==,iv:d8UvuGzdyZGUFtWxuK2d4sU/5EmTDxUT7TtyBck5Wtw=,tag:2V3SjIiZdA06Lz9iaNhTPg==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:UM8Z05rrTQ==,iv:7NMnGQsOUytlKvSNJbDW2G0vYKka2qsqjmFrg/ua1bA=,tag:L023pEJsXzCePCEJ4+T/Fw==,type:str]
    VNC_USER: ENC[AES256_GCM,data:6axZpcY=,iv:IBY3O1hz19j15hVuBucX8NcFTBVWDYuVNiryo5M4uGA=,tag:0Q0GAZY6QZpTJJzBVQCJXw==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:KeeGhHLdEzc=,iv:HqY9w0A/BK+fcYOMNO8ND5H+otWMxII9H9kD5Eq1zNc=,tag:Z96GQVXxJrSnT4SKS6EfMg==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:su+gb0QMOpw=,iv:Vrsx402oeBOPj5inH60lvvaLf/pywwG//4PZvx+YnI4=,tag:Z5SEJWGrYYU34FI9/B9u5A==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:sPeXrRhISI0=,iv:I4n3aALSQVhE2nw5QkvTpJXCs/BzTLTypuww990kGDQ=,tag:M5/s0uKe4vBbp/iGyAn3kg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:AK79aL0=,iv:A/oD6b8aXygVXiSCXb8/Pm8e8LoNZggbu1nrr8RsvlI=,tag:wkJiuLm8E1n/VjKcbuwZrg==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:kM6M3qs150g=,iv:9w4iZj9nlBxA7/vntgryO1hhmcS2ZoZHI2mVil7Iz6E=,tag:+j2YqnS8+grZHGo/EsEwyw==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:G85oag7Z70EccQ==,iv:lhVf2dLXNXoQ8p4WT0skvMLt6SYunRC8uO1uyC6rgLI=,tag:F609+PGIFEWI0E5y6lYc9Q==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:FbyyZTBEDek35KJE8O4JMg==,iv:oPHeYul8o+K8sDyRmeIDOuA/V6ixBXpdad2mRwMUjD0=,tag:g2q63oDocpvlAmmmSTnBBA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:Cg5Fs9XyxAw=,iv:XBTuvy/BlOlaXTRq5Vlc8tUi/5nakuKpv+/TakofB+c=,tag:Roj01fFMxUJZIRFe8LnXhA==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:PojEqwVnnxTX9kTzqkXAFw==,iv:xkKPPGSLZWRCMVkSpce8Ed5v9FhoTHKadbeJFtm2Rns=,tag:4ihfeDKZuW4AE8Wj1nxerg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:kKiM9DneLOfcl0s=,iv:HyWh7znOuuw76ax0TgfY+vExNAwNKc4uk0HlTBgM/eI=,tag:j9B2iFkV7bhu7xnaCrKUWw==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BKqzD0kg7eULetOGpbrlHlVjo7Wq4I3lMTk=,iv:kX/KfUg1Ci38UF6wLiP13w41LNieI0AOiSHjDyyNV28=,tag:71HYxfOsDd47vTXhOh8m0Q==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:ItaBAakZj1QEwvUheltyULGNJtYTug5i2FA=,iv:klOF8ku/0iIjyCv7vVy1CE0Q1293IgxO4DGYEaCdfY4=,tag:hXNysTCh64/6jsIn5ayybQ==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:k29GQLkMtw==,iv:LN8V8Kuk0nfFTpwWGd0o77m5UWBpKLxo7rrCBU9M9aA=,tag:e3fSYflI/hpr1KANoYgV2g==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lBjZqy8ZrEBxCKWvor7d7dl8nc+agLlQzkU=,iv:J+EFqceAujjERLOm0LK3WJUnMHFiDNsZ9VYPrpEVar0=,tag:7hiZHEIuDkZxfpBYzm60ag==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:FyeSPvwIOyfpoD4Z7NgMv4y/CALQTXDsl9RG93DXFrE=,iv:x49zyVGeKV66nlP9CiMWoC0A6wkU5meSwWgX+c4z7ko=,tag:jzKXpfKNl0fglG0Dll4qIA==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:/X4MvxC1L3o=,iv:S+bq4Rjej8Z/CrLnB7XVNXsxUofpsir2PSe6xBNu43s=,tag:IARXZ7OLrLNYxcYbibuQoQ==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:NtQfNOG3RJ0=,iv:4g4kTi5eW4/+S8vuLuw3ilrp126+q/hk2z4QUIJwYjA=,tag:fpAQtQBTGZAaYmeJyKwc1w==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:LS8mmiXLJcmu4wk=,iv:N3EA6awIc902uyO8O2aH2frVCS/bSsYkq/YHz2Cqa0k=,tag:XxKIZTOEiDwmEDdZxs0MEQ==,type:str]
    QNAP: ENC[AES256_GCM,data:uZWn2DzAZKHbHgw=,iv:JfFORGf3QlGN1cixYfjyxGDT8cvKEDMI2vHGJGkyWOw=,tag:x7V5G/ffQoVHH9oIhy7L+A==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:KzyOJw==,iv:Jlk4EeceD8JHU+xBs/qd1kFm7WkjSa6oOUnhEvqRq+4=,tag:ie1Qm5r4PtnoFZnrYBGUpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQmhVNWZLUWRlUDFsM2FX
            MHFBTkhuVGowRlczOGs5dlJDZFRXYW1GT3drCkVldFhmQW4ySENuWDFFMDlvbE56
            M2xYdWR2bUVNbkVYR1IrMENJS1RzSVkKLS0tIHZGZHp6UVBHOFpnby9aSkJFM0Ur
            Skg5cG1WZEl3WmMrdkgwR3lPN0FOdkkKzMSv9/k9t2KlpCtiEA+ido3Z7nyhidRp
            V3H+dOUk3wWUr2JZMwFchEnk9aj98P6HEfrvc7SlvEhCjBV/8TVoGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T01:02:54Z"
    mac: ENC[AES256_GCM,data:7Wq/3ACdAoC3msw4tuBq+lF7MTX3PWbJw0reJtxv1W6fYF///lc0culD6rrp5gvExDKQ5qlTlknWB75c8Gs3VVVFx2PPq+pwBgxZIFb7Mse4Qg5kK/Bm2IyOGovE6/LsRqJjkqirrHHIkShZH9rKOT4Q4/23DF8+wZhYxtNuak4=,iv:V4RUlN6zLVDHCzHBkEExpnGYLaGlLu6bArPVfk8K1a8=,tag:hSGHJz4baW8mdNcHaXpAiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
