apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:ufLku/JY9oqaBXJ0kfNOIpaKHt4z3SBlqlOoNdEBp1+1PRv9AYAQEyrZKpke01vFpJV1FrJ/58fIBHZhsbXOMKxuF1/ir5OSq0Bole9FHnl0xVbyZfp6oM8SgJwSMQ==,iv:WwcaiImI7DzvNLp31G87cMgv+ZaucznoiXRN9r94cxs=,tag:aU9vD8bTO0sfvmcbSpD3WA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:uyA3Vw6J7Bun2OA=,iv:TiTyPyBcFXn26hR6UPVT27E36iEbOZc3jEnba4vJDis=,tag:v0B01LKf1JRm4EZ0EUKkpw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:fjUj6ugJdKjey04tmhORQA==,iv:pxLdX9RBKqjoT/F5HaAWA1t9zy40vfi/KaypcKIvmRo=,tag:Di1y1mM8lMxptCpWWQykrQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HtH+PmD0sSKN/JpdoqzazAGWGnIDuZIreV6uvRXO2yQT+x0U,iv:e85KOWYXFO9NjRbQ1a+bwJQyRpDdcEik8wjbIsLenc4=,tag:HCsf+HY7MZhaxFmDs2Ar3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV0dvcmF1dzFJVVRpN1lS
            azIyUkszKzFXQzY0M0VxaUtqYURPa1JBeTJzCnEyUittRWVzYlFlZ2Q0bXNzY2dE
            OUwxdW1FSkQxNXhXSHY3Y1B3ZkVLVXMKLS0tIEJLYlpZMDVrS05GVnhvM2U1N2RP
            TjZHYTNPRkl0RThkcmt5S0M1ZEdObjgKsvlU7k02WYkTpJLpe+EQS2Cr7eMUzTDn
            oSwkPB4ziGngL+h2deEo0Gw3f58Ykg4fVBhIfopW3Wabv0wynA2zhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T06:24:08Z"
    mac: ENC[AES256_GCM,data:DPymZ/ybmLO/Lh+cOF3uejCFGiTcQUokprOuXD8mljGJP8cnbcNjG4LH2DBxzVaT4HMzz+0i3EejdFDRYXsQoWcqbQVtDRgW79J5DbeDWdmUxYQU1tA1uVwgWm9/UFJeKyKyQm4nj5/8YS89Uq7lEGaBfnW530d8yTRCPev4oRs=,iv:wM+97tx7sZCc11JaxBhvl9FfwL1/Ljyh5lMcj9HntbY=,tag:wgGFaFGrw42UqHxx8Etarg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
