apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kn+i4yxHD1bkcaxXqf/fLEV0YykpSasZdXU9QFGaEBE=,iv:wsdcPoVvbroaPTq9/OYZL29dhkffhesPR8RhMVCFjtg=,tag:kKTOVqKF03ilLaTADF3zhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcCtIV1ZwZ0pnQU9iMW91
            aCtGYWJybVBEWGRWNU94L1hmYTc5U2tjalU4ClhzZUNQQW1WTFlpT0MweDhKTFl3
            ZEFBWDNMYVExNllhbG01Wi9tdTd5MGcKLS0tIDhrL0pnQ3A5VEVQdlVGbm9mcXZG
            a2s0dkMyc1BySitFUGxwQ3liVFpqdUkKJbppAj8EjoCzrV/hfJ6MDXRJ3E6gFQZF
            X+qs/UfWQBxuJVeoYPmvF6d+7ZRn3MyoKSNydRnNu4UP+hj8tWhcug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T19:54:58Z"
    mac: ENC[AES256_GCM,data:REN13znlmNUcn9o/OhbgENjhDteWjr0PYGv1Yc8Vsa3qZxECap3iEl+WMyy+jpPBb3NsQhCP1Wjff2Grxz5i60cZnEetcFZA2675WieZmzHWyi6jNHvyLfacElazSWsPP7OqTiNyPExcKokwCbllQTviITfq24vy30HTGb/2U/4=,iv:8G4N9OoDCp5T+H7RRn1aE5PLnssy+Q/7UzdAWbQBSMQ=,tag:TSsKOGGwGemBC9GnzQLCwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
