apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:2ItCbJJeO9M/pKjTbTdjiiz3p7cd9bYtK7CUoZpsLA==,iv:57+cHB22hHbbQk6VWOfDY8YpExJmuxys18/daP7GWl8=,tag:53tmIMlfqq6a6TJJnjtPuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z3psUE5SeVVFNDRSK1ll
            TmRTbDZBaE84YlhmK3U0dGpKaTBxckNtRHdNCnFLT3lGSVNUaW9TME8vVmdlbFhO
            cnlEb1ZuNFNLaVBWSE9TT1g0djlKeWMKLS0tIEVwdk40RnQwd0RFSG42NDJ0dkc4
            a0N4c0ZvNGlYdG1aZjEweUVQSGpadEUKsuIViKopye857uZu+pzMQmVJoP1kAUEX
            4jADNpPl/qfNdfXbtNZZ1VTIpVuTbqevpU9bjioGUGrqMay69j7mjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T05:19:20Z"
    mac: ENC[AES256_GCM,data:ax4NHc7IrpG7FOIJG/1nXl38V/dBQGgn1z4/8SLy5i3Tg/JjU3F16x5NN5MMek14VOOHXP75FRS285xOOmruY4n6dWo5KdXimLCnc1W/0dmEHgJhNi56KhuEVwT/QC1zfd3IJaxRr6WuQiTj1JFJUImmve1AbbZkOZaRcJLwGnE=,iv:Bs6qg/a1N5nKUHTNuPFU+GSjMQX3cfy5egdP5wsr0yA=,tag:jf5A9kJeHOVe9P9Up0Bvyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
