apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:LUdJr48Lnsab4ZNG8MQNhgFyVePL9QUbdUYSz0rs/YE=,iv:62oGNQXeBAplJDECP9Uk8ChSgTRK9UN1NYHdN5HO6iQ=,tag:FuFDSiu0YoYailWMti1Uug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZysra0YvdXRkc0pGNTNC
            dThWTVF4SmJEZGFDa2ZlcXJ6MTVXcFQ5SDJrCmh2bWJndnpSYkFtRXNyVC8xMWVk
            THk5c3FvcjBaWU8rb1AxQXBUcmhCdjQKLS0tIEZOak43Y3pXT0swcDRBZTFIYXo0
            OVlkZlVUNTMyZnprVW1zWlhUUXVtQncKhomm7XQ/yeBRagFgPNT7mUkxxNMYg3hk
            JGgCIAsxLNLhJiQO5GWb+yInHmN7lvdL3GkH9gOTz92oQF61oY+fsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T07:02:50Z"
    mac: ENC[AES256_GCM,data:c0EZx/YfKBVyn2DBoMrhxxA1E8NaD1Q6dDuIptkw1QYWIlMHNkOQnxFA3AsT26eAR/1MLsnNcDNUknXQrIevHYrsWYr7vCJ+eFMi16iwqvABDYO6EQLIvDkLAopyPaT8hrMLCUvrmTMzVRloUMSV8c3tPgLOjKOyzijJabaH1QU=,iv:df3BMtQ+2YlaK22ozzM4SdyRhlpQqHddcU/nkIZYW0w=,tag:ymFFotOIeh68lXpKLcDhZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
