apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:I+HBaZIYyA2sb4WyNQQVrhOVL15Kf98eoIzThg2zuxXc73/jeipSkg==,iv:YcOA0lE+aI/epFotX7tND8EphKJHZxIahVaHzA6E+Wg=,tag:JGUEHNMgrEkDJEmUcpIS6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ0gvTkJ1cHBZMHdrc05D
            VUh1UCs4b3hDQXlHQ0w1RTFRRGg1OUIvakFzCmpTSXpmS0UrdTdvNE90cE1GdHVn
            dm5YaytmTEFIVEJVR3ZJUEZ0azBGV2MKLS0tIG9oZno5cVNOZTc1RlpLWE1XaE5Z
            U1dJZlM1ZlhBRlhUV1Nia2R6V1YyT0EKIUgofNWCSj3d/6/hpmhlQtCS1XfAUFe3
            qwJ0Tz3r7fzn4PeacNQtPN+OfsU2KpiWPHof4M0eglSPE5af8+pkBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T06:24:08Z"
    mac: ENC[AES256_GCM,data:F0xJMXfaPmOaVHzgIa/dWGLssiCYqdA95T8823TqSZC7ozFwCs4MtmERUizdms9o2c6g/a9gYbnFYBi1c1S6TiyESwuLudlqGIkjvEcVrgliIT2AG3McoBnV3dkBwC7DuaTYswkZYUUE7afLfqXj1bqmNFD1X65I+apu+RJw/Is=,iv:aZV+gMdu9OmIv1r7xPqXcgGbPC5GMwpkUUhYVqgxH8w=,tag:5HhXL71PVecOkLzm5jiiGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
