apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:SBKssyNlwoqAb31fpBLwubXQmWrAVovz3RxoqIw7D9yYvcxKLwv+XA==,iv:+jqvxVtvR3+vPvh0uwrWGy3yZ7SzxjbmMf/++qIzXxc=,tag:H+BEGBtj6udLRt17c7Hzhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nh0lfh38wghdxjj6glvkggrhqap69cl63prcvgguemsgecx5e3xsw8xg54
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlppQkZQMExUNXVNUnlr
            ZmhtVTQ4Tjk3aGprUWhIb29pc1BtT1ZQNzBNClNNekc3UW9PSXRLdFJLODZ3eEI2
            VVNkOWNTeDNZQjRiUTg1VTF5TU9iWHcKLS0tIG5xWVZJek9nSk95a0VsTmh6S1A4
            cG9Wc3cyQmJQWVdwYU1vcHlGTVlzZU0KuJG/oiK8aZoY+1PysrsOzpq4uru15+OM
            /gEroIcrF5ib7n+xKqtkw64TqbVl5bJXZDqUBWk9EMXC938C2tJ8JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T05:19:20Z"
    mac: ENC[AES256_GCM,data:hcqnUV3kubszikpAmr/J/3Bs+aFI0DUDm6K4EvJO9DzgaVQ8LDkzTGBEOScUuBTM2i9+zYMFb28wPtIArsbTgDCiJTRtDV00PyAtBQX5kRPzDWuU6tt+ArGCT+6+kXijO3BdnbRx2X7Ixmc0hOmqgJHhGfWsAMjyN3Ste5N0zXI=,iv:tcKrw1cl+Z+jEKY+sCqVms0JIjgDUW3LL4r2Y9NLGUk=,tag:BH+973kvkbYfx9ON5vMLZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
