apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AkCzFbWaJFPL9LVToaLl3QeN7EQjFObWzPP71x5sqosO8PVcZb4IGw==,iv:Bn3hs+noMms0FFFox0Hoaw7PHzMXaz9BssWa5tC4wFs=,tag:uF6zosBzLPs7JASGHYTIUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yvfl7k5qfn28s0yhe4d446z5ancawxn6sraf2k4vcvxfvh7wvpcqzw47uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHR1NYM1VxVkFaYjl1eitZ
            OTl3Ti9aWkpsMUVvT2F0ZFFQejBodUxtSm5JCkxYbTR4dld1Y2IxUHJxaGRFa1o1
            S1FQWTUzU2llTm5HY0pkV21NUHgxdHMKLS0tIFYzNzNobmdQSXVQVVRSMzlRYTho
            QXI5azVQMm5VOC9Ud3JtY1pUL3pNZ2sKbgo43V7fBGf6oWdpz59s/G+4uNg+Cu0S
            Ax+3gCNUeZTws/JLQhg9NXFvKytlYvh8zXj+1c28rnPp2Ig6KNUU8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T00:59:56Z"
    mac: ENC[AES256_GCM,data:3t08uU05igp3UertzBU6+F/Scfo08wWnOs7L1jglw+/2RSw0qmJz0ZnqssjaarjsFN9ddzho/z3h5EYBofzTp12gul1EFGnYVT2tNcwLa2onldXJPU23INWAHEj7Z7HPkjHI2qWziVIqiHVGJA3MCkjALqrZrAQMdPvqQYH82TQ=,iv:kUN7rF4C2h9pGRabOCGCdx9Iya6LNytnfVcYJRaBAvI=,tag:hQNCStQKt2q93ETI2teKzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
